export enum KernelState {
    PRE_BOOT = 'PRE_BOOT',
    CORE_BOOT = 'CORE_BOOT',
    CONTAINER_SETUP = 'CONTAINER_SETUP',
    MODULE_DISCOVERY = 'MODULE_DISCOVERY',
    REGISTRATION = 'REGISTRATION',
    RESOLUTION = 'RESOLUTION',
    POST_BOOT = 'POST_BOOT',
    ACTIVE = 'ACTIVE',
    SHUTTING_DOWN = 'SHUTTING_DOWN',
    TERMINATED = 'TERMINATED',
    FAILED = 'FAILED'
}
